name: Timer
module: skills.timer.main
category: general
description:
  en: Gives your Wingman the ability to delay actions - be it a reminder, a command or a function call.
  de: Gibt deinem Wingman die Möglichkeit, Aktionen zu verzögern - sei es eine Erinnerung, ein Befehl oder ein Funktionsaufruf.
examples:
  - question:
      en: Remind me in 60 minutes to take a break.
      de: Erinnere mich in 60 Minuten daran, eine Pause zu machen.
    answer:
      en: (Tells you to take a break in 60 minutes)
      de: (Erinnert dich in 60 Minuten daran, eine Pause zu machen)
prompt: |
  You can also delay actions with the `set_timer` function. The function has 3 parameters:

  - The first argument is the time in seconds,
  - the second argument is the function to call
  - the third argument is a list of arguments for the function.

  Only use the `set_timer` function if the user requests to delay a function.
  Never say a timer id, always use a decriptive name.
  When confirming, keep it short and simple.
  When reading out current timers, use the most suitable time unit.
