module: skills.control_windows.main
name: ControlWindows
display_name: Control Windows
author: teddybear082
platforms:
  - windows
tags:
  - Utility
  - Windows
  - launch application
  - open program
  - clipboard
description:
  en: Launch applications and control your Windows computer. Utilize the clipboard of your computer.
  de: Starte Anwendungen und steuere deinen Windows-Computer. Nutze die Zwischenablage deines Computers.
hint:
  en: This skill looks for applications in your Start Menu directory (%APPDATA%/Microsoft/Windows/Start Menu/Programs), so if it tells you that it cannot find an application, create a shortcut in that directory.
  de: Dieser Skill sucht nach Anwendungen in deinem Startmenü-Verzeichnis (%APPDATA%/Microsoft/Windows/Start Menu/Programs). Wenn er dir also sagt, dass er eine Anwendung nicht finden kann, erstelle eine Verknüpfung in diesem Verzeichnis.
