name: InstantActivationLearning
module: skills.instant_activation_learning.main
description:
  en: Analyzes user input with resulting command executions and learns recurring, unique pairs.
  de: Analysiert Eingabenachrichten und resultierende Commands und lernt wiederkehrende, eindeutige Paare.
hint:
  en: Currently it hangs one message behind. Will be fixed in a future release.
  de: Der Analyseprozess hängt aktuell eine Nachricht hinterher. Das wird in einer zukünftigen Version behoben.
custom_properties:
  - id: intant_activation_learning_rule_count
    name: Hits until learn
    hint: The number of times a command got executed by the same phrase before it is learned.
    value: 3
    required: true
    property_type: number