module: skills.radio_chatter.main
name: RadioChatter
api_version: 3
display_name: Radio Chatter
author: JayMatthew
tags:
  - Game
  - Music
auto_activate: true
description:
  en: Randomly playback radio chatter over time. Customize the participants and their voices.
  de: Spielt zufällige Funkgespräche ab. Passe die Teilnehmer und ihre Stimmen an.
discoverable_by_default: false
custom_properties:
  - id: prompt
    name: Prompt for message generation
    hint: The scenario for the generated radio chatter. If empty, a generic radio conversation is used.
    required: false
    value: "Generate a dialog between random pilots in the Star Citizen universe. Feel free to throw in some random details. Keep in mind that Port Olisar does no longer exist."
    property_type: textarea
  - id: voices
    name: Available voices
    hint: The voices used in the radio chatter
    value: []
    required: false
    property_type: voice_selection
    options:
      - label: "multiple"
        value: true
  - id: interval_range
    name: Interval (sec)
    hint: Time between radio chatter events. Also used for the first event.
    value: [60, 600]
    required: true
    property_type: range_slider
    options:
      - label: "min"
        value: 60
      - label: "max"
        value: 600
      - label: "step"
        value: 10
  - id: messages_range
    name: Messages per event
    hint: Number of messages to play per chatter event.
    value: [1, 5]
    required: true
    property_type: range_slider
    options:
      - label: "min"
        value: 1
      - label: "max"
        value: 5
      - label: "step"
        value: 1
  - id: participants_range
    name: Participants
    hint: Number of participants in the chatter.
    value: [2, 3]
    required: true
    property_type: range_slider
    options:
      - label: "min"
        value: 1
      - label: "max"
        value: 5
      - label: "step"
        value: 1
  - id: force_radio_sound
    name: Force radio effect
    hint: Overwrites wingman sound effects for radio chatter with selected radio effects. Needs at least one valid value in "Availale radio effects".
    value: True
    required: false
    property_type: boolean
  - id: radio_sounds
    name: Available radio effects
    hint: Radio effects randomly used when "Force radio effect" is enabled.
    value: "low, medium"
    required: false
    property_type: single_select
    options:
      - label: "Low"
        value: "low"
      - label: "Medium"
        value: "medium"
      - label: "High"
        value: "high"
      - label: "Low & Medium"
        value: "low, medium"
      - label: "Low & High"
        value: "low, high"
      - label: "Medium & High"
        value: "medium, high"
      - label: "All"
        value: "low, medium, high"
  - id: auto_start
    name: Auto start
    hint: Automatically start the radio chatter with your Wingman.
    value: True
    required: false
    property_type: boolean
  - id: volume
    name: Volume
    hint: The volume (relative to the Wingman's volume) of the radio chatter. Must be between 0.0 (silent) and 1.0 (same volume as Wingman).
    value: 0.5
    required: false
    property_type: slider
    options:
      - label: "min"
        value: 0.0
      - label: "max"
        value: 1.0
      - label: "step"
        value: 0.1
  - id: print_chatter
    name: Print chatter
    hint: Print the generated chatter to message overview.
    value: True
    required: false
    property_type: boolean
#  disable knowledge integration for now
#  - id: radio_knowledge
#    name: Radio knowledge
#    hint: If enabled, the radio chatter messages will be added to the Wingman conversation. This way you can talk with your Wingman about the radio chatter.
#    value: False
#    required: false
#    property_type: boolean
  - id: use_beeps
    name: Use beeps
    hint: Use beeps to indicate the start and end of a radio chatter messages.
    value: True
    required: false
    property_type: boolean
