module: skills.auto_screenshot.main
name: AutoScreenshot
display_name: Auto Screenshot
author: teddybear082
tags:
  - Utility
  - Game
description:
  en: Take screenshots on command or automatically when you show excitement.
  de: Mache Screenshots auf Befehl oder automatisch wenn du Aufregung zeigst.
custom_properties:
  - hint: If you have multiple monitors, the display to capture if detecting the active game window fails
    id: display
    name: Display to capture
    property_type: number
    required: true
    value: 1
  - hint: The default directory to put screenshots in. If left blank, it will default to your WingmanAI config directory in a subdirectory called "/screenshots".
    id: default_directory
    name: Default directory
    property_type: string
    required: false
    value: ""
