name: SaveTextToFile
module: skills.save_text_to_file.main
description:
  en: Save text content to a file on your system.
  de: Speichere Textinhalte in einer Datei auf deinem System.
hint:
  en: This skill allows you to save text content to a specified file. You can specify the file name, content, and directory for saving.  Supported file extensions are txt, md, log, yaml, py, and json.  If you do not specify a directory, it will look for the file in your WingmanAI config folder.
  de: Diese Fähigkeit ermöglicht es dir, Textinhalte in einer angegebenen Datei zu speichern. Du kannst den Dateinamen, den Inhalt und das Verzeichnis zum Speichern angeben.  Unterstützte Dateierweiterungen sind txt, md, log, yaml, py und json.  Wenn Sie kein Verzeichnis angeben, wird in Ihrem WingmanAI-Konfigurationsordner nach der Datei gesucht.
examples:
  - question:
      en: Save "Hello, World!" to file "greeting.txt".
      de: Speichere "Hallo, Welt!" in die Datei "greeting.txt".
    answer:
      en: (Saves "Hello, World!" to "greeting.txt" in the default directory)
      de: (Speichert "Hallo, Welt!" in "greeting.txt" im Standardverzeichnis)
  - question:
      en: Save JSON content to a file named "data.json".
      de: Speichere JSON-Inhalte in eine Datei namens "data.json".
    answer:
      en: (Validates and saves JSON content to "data.json" in the default directory)
      de: (Validiert und speichert JSON-Inhalte in "data.json" im Standardverzeichnis)
prompt: |
  This skill saves text content specified by the user to a file.
  The user can specify the file name, directory, and text content to be saved.  If no directory is specified, a default one will be used, which is the WingmanAI config directory.
  JSON content will be validated and formatted before saving.
custom_properties:
  - id: create_file_default_path
    name: Default Path
    hint: The default path where the file should be created if no specific location is provided.  If left blank, it will default to your WingmanAI config folder.
    value: ""
    required: false
    property_type: string
  - id: overwrite_existing
    name: Overwrite Existing File
    hint: Set this option to "true" to allow the AI to overwrite any existing files at the same path as the file you ask the AI to create.  CAUTION - if you mark this true, you should BACK UP any potentially impacted files first.
    value: false
    required: true
    property_type: boolean