name: LoadTextFromFile
module: skills.load_text_from_file.main
description:
  en: Load text content from a file and display it in the AI conversation.
  de: Lade Textinhalte aus einer Datei und zeige diese im AI-Gespräch an.
hint:
  en: This skill allows you to load text content from a specified file and use it in the current AI conversation. You can specify the file name and directory to load from.  Supported file extensions are txt, md, log, yaml, py, and json.  If you do not specify a directory, it will look for the file in your WingmanAI config folder.
  de: Diese Fähigkeit ermöglicht es dir, Textinhalte aus einer angegebenen Datei zu laden und im aktuellen AI-Gespräch anzuzeigen. Du kannst den Dateinamen und das Verzeichnis zum Laden angeben.  Unterstützte Dateierweiterungen sind txt, md, log, yaml, py und json.  Wenn Sie kein Verzeichnis angeben, wird in Ihrem WingmanAI-Konfigurationsordner nach der Datei gesucht.
examples:
  - question:
      en: Load content from file "greeting.txt".
      de: Lade Inhalte aus der Datei "greeting.txt".
    answer:
      en: (Loads content from "greeting.txt" from your WingmanAI config folder and displays it in the conversation)
      de: (Lädt den Inhalt von "greeting.txt" aus Ihrem WingmanAI-Konfigurationsordner und zeigt ihn in der Konversation an)
  - question:
      en: Load JSON content from a file named "data.json" in C:\MyPrograms.
      de: Lade JSON-Inhalte aus einer Datei namens "data.json" in C:\MyPrograms.
    answer:
      en: (Validates and loads JSON content from "data.json" in C:\MyPrograms and displays it in the conversation)
      de: (Validiert und lädt JSON-Inhalte aus "data.json" in C:\MyPrograms und zeigt sie im Gespräch an)
prompt: |
  This skill loads text content from a specified file and displays it in the AI conversation.
  The user can specify the file name and directory to load from. If no directory is specified, a default one will be used, which is the WingmanAI config directory.
  The AI will validate and format the content if it is a JSON file before displaying it.
custom_properties:
  - id: load_file_default_path
    name: Default Path
    hint: The default path where the file should be loaded from if no specific location is provided. If left blank, it will default to your WingmanAI config folder.
    value: ""
    required: false
    property_type: string