module: skills.vision_ai.main
name: VisionAI
display_name: Vision AI
author: ShipBit
tags:
  - Image
  - Utility
  - Game
  - Windows
description:
  en: Let your Wingman analyse whatever is on your screen.
  de: Lass deinen Wingman alles analysieren, was auf deinem Bildschirm zu sehen ist.
custom_properties:
  - id: display
    name: Display to capture
    property_type: number
    required: true
    value: 1
  - id: show_screenshots
    name: Show screenshots
    property_type: boolean
    required: true
    value: true
