{
  "projectId": "5bb2df28-5a58-4d02-84b4-c28cce4e1fa0",
  "filteredQuery": {
    "name": "",
    "statuses": [
      "ACTIVE"
    ],
    "includeIdsInResult": [],
    "sortBy": {
      "field": "NAME",
      "direction": "ASC"
    },
    "paging": {
      "first": 100
    }
  },
  "activeQuery": {
    "statuses": [
      "ACTIVE"
    ],
    "sortBy": {
      "field": "NAME",
      "direction": "ASC"
    },
    "paging": {
      "first": 1
    }
  },
  "allQuery": {
    "sortBy": {
      "field": "NAME",
      "direction": "ASC"
    },
    "paging": {
      "first": 1
    }
  }
}