name: AutoScreenshot
module: skills.auto_screenshot.main
category: general
description:
  en: Take screenshots on command or automatically when you show excitement.
  de: Mache Screenshots auf Befehl oder automatisch wenn du Aufregung zeigst.
examples:
  - question:
      en: Take a screenshot
      de: Mache einen Screenshot
    answer:
      en: (takes a screenshot of the focused window)
      de: (macht einen Screenshot des fokussierten Fensters)
  - question:
      en: Oh wow, this is crazy!
      de: Oh wow, das ist verrückt!
    answer:
      en: (takes a screenshot of the focused window)
      de: (macht einen Screenshot des fokussierten Fensters)
prompt: |
  You can take a screenshot of the focused window when asked by the user. You can also take a screenshot when you infer something important, exciting, scary or interesting is going on where having a screenshot would create a nice memory of the moment for the user.
  Use the 'take_screenshot' tool to capture the screenshot, and provide a reason for why you are doing so, such as because of the request of the user or why you decided it would be good to take a screenshot.
  Example 1: User says something like "oh wow" or "oh no" or "this is crazy!"
  Your response: (use take_screenshot tool with "exciting moment" reason)
  Example 2: User says "take a screenshot"
  Your response: (use take_screenshot tool with "user request" reason)
  Example 3: User says "look at my screen and tell me what you see."
  Your response: (Use VisionAI skill if available, do not call take _screenshot tool. User does not want a screenshot, they want you to look at what they are seeing.)
custom_properties:
  - hint: If you have multiple monitors, the display to capture if detecting the active game window fails
    id: display
    name: Display to capture
    property_type: number
    required: true
    value: 1
  - hint: The default directory to put screenshots in. If left blank, it will default to your WingmanAI config directory in a subdirectory called "/screenshots".
    id: default_directory
    name: Default directory
    property_type: string
    required: false
    value: ""
