name: CreateFolder
module: skills.create_folder.main
description:
  en: Allows your Wingman to create folders at specified locations. Easily organize your directories with simple voice commands.
  de: Ermöglicht deinem Wingman das Erstellen von Ordnern an angegebenen Standorten. Organisiere deine Verzeichnisse einfach per Sprachbefehl.
hint:
  en: This skill allows you to create a folder in a specified directory.  If you do not specify a directory, it will look for the file in your WingmanAI config folder.
  de: Mit diesem Skill können Sie einen Ordner in einem bestimmten Verzeichnis erstellen.  Wenn Sie kein Verzeichnis angeben, wird in Ihrem WingmanAI-Konfigurationsordner nach der Datei gesucht.
examples:
  - question:
      en: Create a folder named "Projects" in C:\WingmanAIFiles.
      de: Erstelle einen Ordner namens "Projekte" in C:\WingmanAIFiles.
    answer:
      en: (creates a folder named "Projects" in C:\WingmanAIFiles.)
      de: (erstellt einen Ordner namens "Projekte" in C:\WingmanAIFiles)
  - question:
      en: Make a new directory called "Backups".
      de: Erstelle ein neues Verzeichnis namens "Backups".
    answer:
      en: (creates a folder named "Backups" in the default directory)
      de: (erstellt einen Ordner namens "Backups" im Standardverzeichnis)
  - question:
      en: Create a folder called "Music" in C:\Users\John\Documents.
      de: Erstelle einen Ordner namens "Musik" in C:\Users\John\Documents.
    answer:
      en: (creates a folder named "Music" in C:\Users\John\Documents)
      de: (erstellt einen Ordner namens "Musik" in C:\Users\John\Documents)
prompt: |
  The `create_folder` function allows you to create folders in specified locations. The function has 2 parameters:

  - The first argument is the path where the folder should be created (e.g., "C:\MyDocuments").  If none is specified you will use a default location.
  - The second argument is the name of the folder to create (e.g., "Projects").

  Use the `create_folder` function only when the user requests to create a folder.
custom_properties:
  - id: create_folder_default_path
    name: Default Path
    hint: The default path where the folder should be created if no specific location is provided.  If left blank, will default to the WingmanAI config folder.
    value: ""
    required: false
    property_type: string
