'use strict';
const $ = (id) => document.getElementById(id);
const state = {section:'overview',mode:'simple',offset:0,rows:[],overview:{},loading:false};
const tabs = [['overview','Overview'],['operations','Operations'],['journal','Money'],['inventory','Cargo'],['assets','Assets'],['attention','Attention'],['production','Production','advanced'],['plans','Planning','advanced'],['evidence','Evidence','advanced'],['reports','Reports','advanced'],['history','History','advanced']];
const titles = Object.fromEntries(tabs.map(t=>[t[0],t[1]]));
const descriptions = {operations:'Keep every trip, contract and session together, from its first expense to its final sale.',journal:'Cash movement and corrections. Profit also accounts for the cost of the goods you sell.',inventory:'Your recorded cargo, its location and its cost. Unknown purchase costs remain unknown.',assets:'Your fleet and equipment, with the acquisition details you have recorded.',attention:'Review uncertain events and fill the gaps that affect your accounts.',production:'Follow goods through processing, completion and collection.',plans:'Set your targets, protect your operating reserve and record committed funds.',evidence:'Trace observations back to the game feed. A request alone does not confirm a completed transaction.'};
const forms = {};
const f = (key,label,type='text',extra={})=>({key,label,type,...extra});
const nameField=()=>f('name','Name','text',{required:true});
const amount=(key='amount',label='Amount (aUEC)',required=true)=>f(key,label,'number',{required,min:'0',step:'any'});
const qty=()=>f('quantity','Quantity','number',{required:true,min:'0.000001',step:'any'});
const operation=()=>f('operation_id','Operation','relation',{section:'operations',optionalLabel:'No operation'});
const note=()=>f('notes','Notes','textarea');
forms.start_operation={title:'Start an operation',fields:[nameField(),f('activity','Activity','select',{options:['hauling','mining','salvage','mission','other']}),amount('budget','Budget (aUEC)',false)]};
forms.finish_operation={title:'Finish operation',description:'Close this operation. Its records remain available.',fields:[]};
forms.record_cash={title:'Record money',fields:[f('direction','Direction','select',{options:['income','expense']}),amount(),f('category','Category','text',{required:true,value:'other'}),operation(),f('asset_id','Asset','relation',{section:'assets',optionalLabel:'No asset'}),note()]};
forms.buy_stock={title:'Record cargo purchase',description:'Leave the cost blank when it is unknown. Enter zero only for goods obtained at no cost.',fields:[f('item_name','Item name','text',{required:true}),f('item_id','Item identifier','text',{hint:'Optional; defaults to the item name.'}),qty(),f('unit','Unit','select',{options:['SCU','units','kg']}),f('location','Location','text',{required:true}),amount('amount','Total purchase cost (aUEC)',false),operation(),f('owner','Owner','select',{options:['personal','mission','other']})]};
forms.sell_stock={title:'Record cargo sale',fields:[qty(),amount('amount','Total sale proceeds (aUEC)'),operation()]};
forms.reserve_stock={title:'Reserve cargo',description:'Set the total quantity reserved in this lot. Enter zero to release it.',fields:[f('quantity','Reserved quantity','number',{required:true,min:'0',step:'any'})]};
forms.transfer_stock={title:'Move cargo',fields:[qty(),f('destination','Destination','text',{required:true})]};
forms.lose_stock={title:'Record cargo loss',description:'Remove lost stock and record its known cost as a loss.',fields:[qty()]};
forms.register_asset={title:'Add an asset',description:'For an existing asset, the price is historical information. Mark a new purchase only when cash should be spent now.',fields:[nameField(),amount('purchase_price','Purchase price (aUEC)',false),f('acquired_now','This is a new cash purchase','checkbox')]};
forms.update_asset={title:'Update asset',fields:[f('status','Status','select',{options:['active','unavailable','destroyed','sold']}),amount('sale_amount','Sale proceeds (when sold)',false),note()]};
forms.start_production={title:'Start processing',description:'Select the input lots and quantities used. Processing fees are paid now.',fields:[nameField(),f('inputs','Input cargo','inputs',{required:true}),amount('fee','Processing fee (aUEC)'),operation()]};
forms.complete_production={title:'Mark processing complete',description:'The job will be ready for collection. Output cargo is recorded when you collect it.',fields:[]};
forms.collect_production={title:'Collect output',fields:[f('item_name','Output item','text',{required:true}),f('item_id','Item identifier'),qty(),f('unit','Unit','select',{options:['SCU','units','kg']}),f('location','Collection location','text',{required:true})]};
forms.set_plan={title:'Set a savings plan',fields:[nameField(),amount('target','Target (aUEC)'),amount('reserve','Operating reserve (aUEC)'),amount('committed','Committed funds (aUEC)')]};
forms.reconcile_wallet={title:'Reconcile wallet',description:'Enter the balance you currently see in the game. The difference is recorded as an adjustment with your note.',fields:[amount('amount','Observed wallet balance (aUEC)'),note()]};
forms.reverse_entry={title:'Reverse an entry',description:'A correcting entry preserves the original history. Related stock movements may need to be corrected first.',fields:[f('reason','Reason','textarea',{required:true})]};
forms.new_period={title:'Start a new period',description:'Begin a separate accounting period, for example after a wipe. Existing history is retained.',fields:[nameField(),f('confirmed','Start empty books and retain existing history','checkbox',{required:true})]};
forms.set_stock_cost={title:'Record remaining cargo cost',description:'Set the cost basis for the quantity remaining in this lot. This updates stock valuation without recording another cash payment.',fields:[amount('amount','Total cost of remaining stock (aUEC)')]};
forms.resolve_cost={title:'Record consumed stock cost',description:'Enter the cost of goods already sold or lost. Cash remains unchanged.',fields:[amount('amount','Cost of goods consumed (aUEC)')]};
forms.allocate_sale={title:'Match sale to cargo',description:'Select the lots and quantities sold. Sale proceeds were already recorded; this assigns stock cost without recording cash twice.',fields:[f('inputs','Cargo sold','inputs',{required:true})]};
forms.assign_entry={title:'Assign transaction',description:'Connect this transaction to its operation and, when relevant, the asset it belongs to.',fields:[operation(),f('asset_id','Asset','relation',{section:'assets',optionalLabel:'No asset'})]};
forms.resolve_event={title:'Resolve observed event',description:'Confirm only what you can verify. Choose dismiss to retain the evidence without posting a transaction.',fields:[f('decision','Decision','select',{options:['dismiss','confirm']}),f('direction','Cash direction','select',{options:['income','expense']}),amount('amount','Confirmed amount (aUEC)',false),f('category','Category','text',{value:'other'}),operation(),note()]};
forms.set_plan.description='Forecasts use the explicit assumptions entered here. Leave assumptions blank when unknown; quantities must use the same unit.';
forms.set_plan.fields.push(amount('income_per_hour','Income per hour (aUEC)',false),amount('cost_per_hour','Cost per hour (aUEC)',false),f('hours_per_week','Hours per week','number',{min:'0',step:'any'}),f('required_quantity','Quantity required','number',{min:'0',step:'any'}),f('available_quantity','Quantity available','number',{min:'0',step:'any'}),f('capacity_per_trip','Capacity per trip','number',{min:'0',step:'any'}));
descriptions.history='Earlier accounting periods and current history, preserved for reference. Historical entries are read-only here.';
descriptions.reports='Financial summaries of recorded activity. Missing costs and values remain visible; these are not a complete game account statement.';
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=String(text);if(className)e.className=className;return e;}
function button(text,fn,className){const e=node('button',text,className);e.type='button';e.addEventListener('click',fn);return e;}
function money(value){if(value===null||value===undefined||value==='')return 'Unknown';const text=String(value);const parts=text.split('.');parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,',');return parts.join('.');}
function label(key){return key.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
const cashFields=new Set(['cash','profit','budget','cash_flow','realized_profit','spending','budget_remaining','profit_per_hour','purchase_price','running_cost','remaining_to_break_even','cost','total_cost','unit_cost','fee','target','reserve','committed','shortfall','income_per_hour','cost_per_hour']);
function displayValue(key,value){if(value===null)return 'Unknown';if(typeof value==='boolean')return value?'Yes':'No';if(cashFields.has(key))return money(value)+' aUEC';if(key==='timestamp'||key.endsWith('_at')){const date=new Date(value);return Number.isNaN(date.valueOf())?String(value):date.toLocaleString();}return typeof value==='string'?value.replace(/_/g,' '):String(value);}
const simpleKeys={operations:['activity','realized_profit','spending','profit_complete'],journal:['cash','profit','notes','timestamp','unknown_cost'],inventory:['quantity','reserved','unit','location','owner','cost'],assets:['purchase_price','running_cost','notes']};
function toast(message,error=false){const e=$('toast');e.textContent=message;e.className=error?'error':'';e.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{e.hidden=true;},6000);}
async function api(path,options={}){const res=await fetch(path,options);let data;try{data=await res.json();}catch{throw new Error('The dashboard is unavailable. Refresh after Wingman reconnects.');}if(!res.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check the entered values and try again.');return data;}
async function command(action,data){return api('/api/erp/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})});}
async function read(section,offset=0){return api(`/api/erp/${section}?limit=100&offset=${offset}`);}
function rows(data){if(Array.isArray(data))return data;if(data&&Array.isArray(data.items))return data.items;if(data&&Array.isArray(data.rows))return data.rows;return [];}
function nav(){const target=$('navigation');target.replaceChildren();for(const [key,title,tier] of tabs){if(tier&&state.mode!==tier)continue;const b=button('',()=>{if(state.loading)return;state.section=key;state.offset=0;load();},state.section===key?'active':'');b.append(node('span',String(tabs.findIndex(t=>t[0]===key)+1).padStart(2,'0'),'nav-number'),node('span',title));if(key==='attention'&&state.overview.attention?.length)b.append(node('span',state.overview.attention.length,'badge pending'));b.setAttribute('aria-current',state.section===key?'page':'false');target.append(b);}}
function empty(title,detail){const e=node('div',null,'empty');e.append(node('strong',title),node('span',detail));return e;}
function panel(title){const e=node('section',null,'panel');e.append(node('h2',title));return e;}
function metric(title,value,noteText){const e=node('div',null,'metric');e.append(node('div',title,'metric-label'),node('div',money(value),'metric-value'),node('div','aUEC','metric-unit'),node('div',noteText,'metric-note'));return e;}
function overview(data){const content=$('content');const hero=node('section',null,'hero');const intro=node('div');intro.append(node('span','READY FOR YOUR NEXT RUN','eyebrow'),node('h2','Make every operation count.'),node('p','Keep money, cargo and jobs together. Your game feed adds observations; you fill in what the game cannot confirm.'));hero.append(intro,button('Start an operation',()=>openForm('start_operation'),'primary'));content.append(hero);
const metrics=node('section',null,'metrics');metrics.append(metric('Recorded balance',data.balance,'Reconcile against your in-game wallet.'),metric('Cash movement',data.cash_flow,'Money received minus money paid.'),metric('Realised profit',data.realized_profit,'Based on recorded costs and revenue.'),metric('Stock at cost',data.inventory_cost,'Known cost of stock and goods in processing.'));content.append(metrics);
if(Number(data.unknown_cost_quantity)>0||data.profit_complete===false)content.append(node('div','Some goods have an unknown purchase cost. Recorded profit may be incomplete; review the items needing attention.','notice'));
const grid=node('div',null,'grid-two');const ops=panel('Your operations');const operations=rows(data.operations);operations.length?operations.slice(0,4).forEach(r=>ops.append(record(r,'operations'))):ops.append(empty('No operations yet','Start a trip or a job to keep its costs and results together.'));const attention=panel('Needs attention');const events=rows(data.attention);events.length?events.slice(0,4).forEach(r=>attention.append(record(r,'attention'))):attention.append(empty('Nothing waiting for review','Uncertain feed events will appear here.'));grid.append(ops,attention);content.append(grid);
const quick=panel('Your next step');const actions=node('div',null,'actions');for(const [action,title] of [['record_cash','Record money'],['buy_stock','Add cargo'],['reconcile_wallet','Reconcile wallet']])actions.append(button(title,()=>openForm(action)));if(state.mode==='advanced')actions.append(button('Start a new period',()=>openForm('new_period')));quick.append(actions);if(data.feed&&Object.keys(data.feed).length){const feed=data.feed;quick.append(node('p',`Game feed: ${feed.status==='connected'?'Reader database connected; game activity not verified':(feed.status==='not_connected'?'No reader connected':(feed.status||feed.state||'configured'))}${feed.last_sync?' · Last sync '+feed.last_sync:''}${feed.error?' · '+feed.error:''}`,'feed'));}else quick.append(node('p','Game feed: no sync information yet. You can record activity manually.','feed'));content.append(quick);
if(state.mode==='advanced'){const plan=node('section',null,'metrics');plan.append(metric('Committed funds',data.committed_funds,'Funds already assigned to plans.'),metric('Available funds',data.available_funds,'After recorded reserves and commitments.'));content.append(plan);}}
const preferred={operations:['activity','budget','cash_flow','realized_profit','spending','budget_remaining','profit_complete','hours','profit_per_hour','status','started_at','ended_at'],journal:['cash','profit','category','operation_id','notes','timestamp','reverses','unknown_cost'],inventory:['item_name','quantity','reserved','unit','location','owner','total_cost','cost','unit_cost','operation_id'],assets:['purchase_price','running_cost','status','notes'],production:['status','fee','operation_id','created_at'],plans:['target','reserve','committed','shortfall','affordable'],attention:['kind','event_type','reason','status','observed_at'],evidence:['kind','event_type','erp_status','reason','source','observed_at']};
preferred.assets.push('realized_profit','profit_complete','remaining_to_break_even','location','attribution');
preferred.plans.push('income_per_hour','cost_per_hour','hours_per_week','required_quantity','available_quantity','capacity_per_trip','expected_hours','estimated_weeks','trips_needed','resource_shortfall');
preferred.history=['period','cash','profit','category','operation_id','notes','timestamp','reverses','unknown_cost'];
function record(r,section){const card=node('article',null,'record');const top=node('div',null,'record-top');const title=r.name||r.item_name||r.category||r.event_type||r.kind||r.reason||'Record';top.append(node('h3',title));if(r.status)top.append(node('span',r.status,'badge '+(['pending','unresolved','unknown'].includes(r.status)?'pending':'')));card.append(top);const dl=node('dl',null,'details');const keys=(state.mode==='simple'&&simpleKeys[section])||preferred[section]||[];for(const key of keys){if(r[key]===undefined||(r[key]!==null&&typeof r[key]==='object')||r[key]===title||key==='status')continue;const cell=node('div');cell.append(node('dt',label(key)),node('dd',displayValue(key,r[key])));dl.append(cell);}card.append(dl);if(state.mode==='advanced'&&r.id)card.append(node('div',r.id,'id'));
const actions=node('div',null,'actions');const add=(action,title,defaults={})=>actions.append(button(title,()=>openForm(action,defaults)));
if(section==='operations'&&r.status==='active')add('finish_operation','Finish',{operation_id:r.id});
if(section==='inventory'&&Number(r.quantity)>0){if(r.cost===null)add('set_stock_cost','Set missing cost',{lot_id:r.id});add('sell_stock','Sell',{lot_id:r.id});add('transfer_stock','Move',{lot_id:r.id});add('reserve_stock','Reserve',{lot_id:r.id});add('lose_stock','Record loss',{lot_id:r.id});}
if(section==='assets')add('update_asset','Update',{asset_id:r.id});
if(section==='production'){if(['processing','active','in_progress'].includes(r.status))add('complete_production','Mark complete',{production_id:r.id});if(['completed','complete','ready'].includes(r.status))add('collect_production','Collect',{production_id:r.id});}
if(section==='attention'&&r.id){if(r.type==='event'){if(r.cash_posted){card.append(node('p','Cash is already recorded. Match the transaction to its cargo; do not confirm another payment.','muted'));if((r.event_type||r.name)==='commodity_sell'&&r.entry_id)add('allocate_sale','Match sold cargo',{entry_id:r.entry_id});else actions.append(button('Open money',()=>{state.section='journal';state.offset=0;load();}));}else add('resolve_event','Review',{event_id:r.event_id||r.id});}else if(r.type==='inventory')add('set_stock_cost','Set missing cost',{lot_id:r.id});else if(r.name==='commodity_sell')add('allocate_sale','Match sold cargo',{entry_id:r.id});else if(['stock_sale','stock_loss','asset_sale'].includes(r.name))add('resolve_cost','Set consumed cost',{entry_id:r.id});else actions.append(button('Open money',()=>{state.section='journal';state.offset=0;load();}));}
if(section==='journal'&&!r.reversed_by&&!r.reverses){add('assign_entry','Assign',{entry_id:r.id,operation_id:r.operation_id});if(r.unknown_cost){if(r.category==='commodity_sell')add('allocate_sale','Match sold cargo',{entry_id:r.id});else if(['stock_sale','stock_loss','asset_sale'].includes(r.category))add('resolve_cost','Set consumed cost',{entry_id:r.id});}if(state.mode==='advanced')add('reverse_entry','Reverse',{entry_id:r.id});}
if(section==='plans')add('set_plan','Edit plan',{id:r.id,...Object.fromEntries(forms.set_plan.fields.map(field=>[field.key,r[field.key]]))});card.append(actions);if(state.mode==='advanced'||section==='attention'){const evidence=node('details');evidence.append(node('summary','Record details'),node('pre',JSON.stringify(r,null,2)));card.append(evidence);}return card;}
const sectionActions={operations:[['start_operation','Start operation']],journal:[['record_cash','Record money'],['reconcile_wallet','Reconcile wallet']],inventory:[['buy_stock','Add cargo']],assets:[['register_asset','Add asset']],production:[['start_production','Start processing']],plans:[['set_plan','Set plan']]};
function listing(data){const content=$('content');const toolbar=node('div',null,'toolbar');toolbar.append(node('p',descriptions[state.section],'muted'));const actions=node('div',null,'actions');for(const [action,title] of sectionActions[state.section]||[])actions.append(button(title,()=>openForm(action),'primary'));toolbar.append(actions);content.append(toolbar);const list=panel(titles[state.section]);state.rows=rows(data);if(!state.rows.length)list.append(empty('No records here yet',state.section==='attention'?'Any uncertain game events will wait here for your review.':'Add a record to begin. Your history will appear here.'));else state.rows.forEach(r=>list.append(record(r,state.section)));content.append(list);const pager=node('div',null,'pager');if(state.offset){pager.append(button('Previous',()=>{state.offset=Math.max(0,state.offset-100);load();}));}pager.append(node('span',state.rows.length?`Records ${state.offset+1}–${state.offset+state.rows.length}`:'0 records'));if(state.rows.length===100)pager.append(button('Next',()=>{state.offset+=100;load();}));content.append(pager);}
function reports(data){const content=$('content');content.append(node('p',descriptions.reports,'muted'));if(data.income_statement?.profit_complete===false)content.append(node('div','Recorded profit is incomplete because one or more costs are unknown.','notice'));const grid=node('div',null,'grid-two');for(const [key,title] of [['cash_flow','Cash flow'],['income_statement','Income statement'],['balance_sheet','Recorded assets and obligations']]){const group=panel(title);const details=node('dl',null,'details');for(const [name,value] of Object.entries(data[key]||{})){const cell=node('div');cell.append(node('dt',label(name)),node('dd',typeof value==='boolean'?(value?'Yes':'No'):(typeof value==='string'&&/^-?\d+(\.\d+)?$/.test(value)?money(value)+' aUEC':String(value))));details.append(cell);}group.append(details);grid.append(group);}const activities=panel('Recorded activity results');const activityRows=rows(data.activities);if(!activityRows.length)activities.append(empty('No activity results yet','Link transactions to operations to compare activities.'));for(const row of activityRows){const entry=node('article',null,'record');entry.append(node('h3',label(row.activity||'Other')),node('p','Cash movement: '+money(row.cash_flow)+' aUEC · Realised profit: '+money(row.realized_profit)+' aUEC','muted'));if(row.profit_complete===false)entry.append(node('span','Profit incomplete','badge pending'));activities.append(entry);}grid.append(activities);content.append(grid);}
async function load(quiet=false){if(state.loading)return;state.loading=true;$('refresh').disabled=true;$('mode').disabled=true;try{const result=await read(state.section,state.offset);state.mode=result.mode||state.mode;if(state.section==='overview')state.overview=result.data||{};if(state.mode==='simple'&&tabs.find(t=>t[0]===state.section)?.[2]){state.section='overview';state.offset=0;state.loading=false;return load();}$('mode').value=state.mode;$('page-title').textContent=titles[state.section];nav();$('content').replaceChildren();state.section==='overview'?overview(result.data||{}):state.section==='reports'?reports(result.data||{}):listing(result.data);}catch(error){if(!quiet)toast(error.message,true);if(!$('content').children.length)$('content').append(empty('Records are unavailable',error.message));}finally{state.loading=false;$('refresh').disabled=false;$('mode').disabled=false;}}
async function relationOptions(section){const result=await read(section);return rows(result.data).map(r=>({value:r.id,label:[r.name||r.item_name||r.id,r.location,r.quantity!==undefined?`${r.quantity} ${r.unit||''}`:''].filter(Boolean).join(' · ')}));}
async function openForm(action,defaults={}){const config=forms[action];if(!config)return;const dialog=$('action-dialog');$('dialog-title').textContent=config.title;$('dialog-description').textContent=config.description||'';$('form-error').textContent='';$('form-fields').replaceChildren();$('dialog-save').disabled=true;dialog.showModal();try{for(const field of config.fields){const wrapper=node('label',null,`field ${['textarea','inputs'].includes(field.type)?'wide':''} ${field.type==='checkbox'?'checkbox':''}`);wrapper.append(node('span',field.label));let input;if(field.type==='inputs'){input=node('div');input.id='production-inputs';const options=await relationOptions('inventory');const addRow=()=>{const row=node('div',null,'actions');const select=node('select');select.setAttribute('aria-label','Input cargo lot');select.required=true;for(const opt of options){const o=node('option',opt.label);o.value=opt.value;select.append(o);}const quantity=node('input');quantity.type='number';quantity.min='0.000001';quantity.step='any';quantity.placeholder='Quantity';quantity.required=true;quantity.setAttribute('aria-label','Input quantity');row.append(select,quantity,button('Remove',()=>row.remove()));input.append(row);};addRow();wrapper.append(input,button('Add another input',addRow));$('form-fields').append(wrapper);continue;}
if(field.type==='select'||field.type==='relation'){input=node('select');const options=field.type==='relation'?await relationOptions(field.section):field.options.map(v=>({value:v,label:label(v)}));if(field.type==='relation'){const o=node('option',field.optionalLabel||'Select a record');o.value='';input.append(o);}for(const opt of options){const o=node('option',opt.label);o.value=opt.value;input.append(o);}}
else if(field.type==='textarea'){input=node('textarea');input.rows=3;}
else{input=node('input');input.type=field.type;}
input.name=field.key;input.setAttribute('aria-label',field.label);input.required=!!field.required;if(field.min!==undefined)input.min=field.min;if(field.step)input.step=field.step;if(field.value!==undefined)input.value=field.value;if(defaults[field.key]!==undefined)input.value=defaults[field.key];wrapper.append(input);if(field.hint)wrapper.append(node('small',field.hint));$('form-fields').append(wrapper);}
$('action-form').onsubmit=async event=>{event.preventDefault();const data={...defaults};for(const field of config.fields){if(field.type==='inputs'){data.inputs=[...$('production-inputs').children].map(row=>({lot_id:row.querySelector('select').value,quantity:row.querySelector('input').value}));continue;}const input=$('action-form').elements.namedItem(field.key);if(field.type==='checkbox')data[field.key]=input.checked;else if(input.value.trim()!=='')data[field.key]=input.value.trim();}if(['buy_stock','collect_production'].includes(action)&&!data.item_id)data.item_id=data.item_name;$('dialog-save').disabled=true;$('form-error').textContent='';try{await command(action,data);dialog.close();toast('Record saved.');await load();}catch(error){$('form-error').textContent=error.message;}finally{$('dialog-save').disabled=false;}};$('dialog-save').disabled=false;const first=$('form-fields').querySelector('input,select,textarea');if(first)first.focus();}catch(error){$('form-error').textContent=error.message;}}
$('dialog-close').addEventListener('click',()=>$('action-dialog').close());$('dialog-cancel').addEventListener('click',()=>$('action-dialog').close());$('refresh').addEventListener('click',()=>load());$('mode').addEventListener('change',async()=>{const selected=$('mode').value;$('mode').disabled=true;try{await command('set_mode',{mode:selected});state.mode=selected;await load();toast(`${label(selected)} workspace selected. Your records are preserved.`);}catch(error){$('mode').value=state.mode;toast(error.message,true);}finally{$('mode').disabled=false;}});load();

setInterval(()=>{if(!document.hidden&&!$('action-dialog').open&&!state.loading)load(true);},5000);
