#!/usr/bin/env python3
"""Raise the version everywhere it is written down, and start the migration.

    python scripts/bump_version.py 3.2.1
    python scripts/bump_version.py 3.3.0 --client ../wingman-client
    python scripts/bump_version.py 3.2.1 --check

The version lives in eight places across two repositories and nothing keeps them
in step. That is not hypothetical: 3.2.0 shipped with `src-tauri/Cargo.toml` and
`Cargo.lock` still reading 3.1.6, because a bump means editing six files in the
client by hand and two of them are Rust.

What it does:

* Core: `LOCAL_VERSION` in `services/system_manager.py`.
* Core: a skeleton migration `services/migrations/migration_<old>_to_<new>.py`,
  which the chain picks up by itself — the loader scans the directory, so there
  is nothing to register. An empty one is correct and worth having: without it a
  user upgrading from the previous version has no entry in the chain at all.
* Client, if a checkout is there: `package.json`, both places in
  `package-lock.json`, `src-tauri/tauri.conf.json`, `src-tauri/Cargo.toml` and
  the `WingmanAI` entry in `src-tauri/Cargo.lock`.

`src/api/core/OpenAPI.ts` is deliberately not touched. It is generated by
`npm run generate:api` and takes its version from the running Core, so it
follows on its own once Core is bumped and restarted.

With `--check` nothing is written; it reports what disagrees and exits non-zero.
That is the form for CI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def underscored(version: str) -> str:
    """3.2.1 -> 3_2_1, the form the migration files and markers use."""
    return version.replace(".", "_")


def class_suffix(version: str) -> str:
    """3.2.1 -> 321, the form the migration class names use."""
    return version.replace(".", "")


def parse(version: str) -> tuple[int, int, int]:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", version)
    if not match:
        raise SystemExit(f"'{version}' is not a version of the form 3.2.1.")
    return tuple(int(part) for part in match.groups())  # type: ignore[return-value]


# ── the places a version is written ───────────────────────────────────


class Spot:
    """One file that carries the version.

    The pattern always captures the version itself in group 1, and writing
    replaces just that group inside whatever the whole match was. One pattern
    then serves both reading and writing — the earlier shape had a separate
    write template, and two of the six quietly read back their own prefix
    instead of the version.
    """

    def __init__(self, label: str, path: Path, pattern: str):
        self.label = label
        self.path = path
        self.pattern = re.compile(pattern)

    @property
    def exists(self) -> bool:
        return self.path.is_file()

    def read(self) -> str | None:
        if not self.exists:
            return None
        match = self.pattern.search(self.path.read_text())
        return match.group(1) if match else None

    def write(self, version: str) -> bool:
        """Returns True when the file changed."""
        text = self.path.read_text()

        def swap(match: re.Match) -> str:
            whole, found = match.group(0), match.group(1)
            # Replace the captured version inside the match, not everywhere:
            # `3.2.0` may well appear elsewhere in the same line.
            at = match.start(1) - match.start(0)
            return whole[:at] + version + whole[at + len(found):]

        new_text, count = self.pattern.subn(swap, text, count=1)
        if count != 1:
            raise SystemExit(f"{self.label}: could not find the version to replace.")
        if new_text == text:
            return False
        self.path.write_text(new_text)
        return True


def core_spots() -> list[Spot]:
    return [
        Spot(
            "core: system_manager.py",
            ROOT / "services/system_manager.py",
            r'LOCAL_VERSION = "([\d.]+)"',
        )
    ]


def client_spots(client: Path) -> list[Spot]:
    return [
        Spot(
            "client: package.json",
            client / "package.json",
            r'"version": "([\d.]+)"',
        ),
        # Two entries, the root one and the one under `packages[""]`. npm keeps
        # them identical and so must we, or `npm ci` rewrites the file.
        Spot(
            "client: package-lock.json (root)",
            client / "package-lock.json",
            r'"name": "@shipbit/wingman-ui",\s*"version": "([\d.]+)"',
        ),
        Spot(
            "client: tauri.conf.json",
            client / "src-tauri/tauri.conf.json",
            r'"version": "([\d.]+)"',
        ),
        Spot(
            "client: Cargo.toml",
            client / "src-tauri/Cargo.toml",
            r'(?m)^version = "([\d.]+)"',
        ),
        Spot(
            "client: Cargo.lock",
            client / "src-tauri/Cargo.lock",
            r'name = "WingmanAI"\nversion = "([\d.]+)"',
        ),
    ]


def read_lock_package_version(client: Path) -> str | None:
    """`packages[""].version` in package-lock.json, which the regex above misses."""
    path = client / "package-lock.json"
    if not path.is_file():
        return None
    data = json.loads(path.read_text())
    return data.get("packages", {}).get("", {}).get("version")


def write_lock_package_version(client: Path, version: str) -> bool:
    """Edited as text, not re-serialised: npm writes this file and rewriting it
    from parsed JSON would reformat five thousand lines."""
    path = client / "package-lock.json"
    text = path.read_text()
    pattern = re.compile(r'("": \{\s*"name": "@shipbit/wingman-ui",\s*"version": ")[\d.]+"')
    new_text, count = pattern.subn(lambda m: f'{m.group(1)}{version}"', text, count=1)
    if count != 1:
        raise SystemExit('client: package-lock.json: could not find packages[""].version.')
    if new_text == text:
        return False
    path.write_text(new_text)
    return True


# ── the migration skeleton ────────────────────────────────────────────

SKELETON = '''"""Migration from version {old} to {new}.

TODO: say what changes in a user's config, and why. If nothing changes, say that
— an empty migration is a normal thing to ship and the sentence explaining why is
what stops the next person wondering whether it was forgotten.

Every `migrate_*` method is optional: the base class returns the config
unchanged, so an empty migration is a valid one. Override only what you need.
"""

from services.migrations.base_migration import BaseMigration


class Migration{old_class}To{new_class}(BaseMigration):
    """Migration from {old} to {new}."""

    old_version = "{old_under}"
    new_version = "{new_under}"
'''


def write_migration(old: str, new: str) -> Path | None:
    # The file name uses the compact form (migration_316_to_320.py), the
    # attributes inside use underscores ("3_1_6"). Both conventions are in the
    # existing files; getting the file name wrong means the loader never sees it.
    path = ROOT / f"services/migrations/migration_{class_suffix(old)}_to_{class_suffix(new)}.py"
    if path.exists():
        return None
    path.write_text(
        SKELETON.format(
            old=old,
            new=new,
            old_class=class_suffix(old),
            new_class=class_suffix(new),
            old_under=underscored(old),
            new_under=underscored(new),
        )
    )
    return path


# ── commands ──────────────────────────────────────────────────────────


def gather(client: Path | None) -> list[tuple[str, str | None]]:
    spots: list[Spot] = core_spots()
    if client:
        spots += client_spots(client)
    found = [(spot.label, spot.read()) for spot in spots if spot.exists]
    if client:
        found.append(("client: package-lock.json (packages)", read_lock_package_version(client)))
    return found


def do_check(client: Path | None, expected: str | None) -> int:
    found = gather(client)
    versions = {version for _, version in found if version}

    # With no agreement, the most common value is the target so the odd ones out
    # are the ones marked. Calling all seven WRONG tells the reader nothing.
    if expected:
        target = expected
    elif len(versions) == 1:
        target = next(iter(versions))
    else:
        counts: dict[str, int] = {}
        for _, version in found:
            if version:
                counts[version] = counts.get(version, 0) + 1
        target = max(counts, key=counts.get) if counts else None

    width = max(len(label) for label, _ in found)
    for label, version in found:
        mark = "ok  " if version and version == target else "WRONG"
        print(f"{mark} {label.ljust(width)}  {version or '(not found)'}")

    if len(versions) == 1 and (expected is None or versions == {expected}):
        print(f"\nAll {len(found)} places agree on {target}.")
        return 0

    print(f"\nThese do not agree: {', '.join(sorted(v for v in versions if v))}")
    print("Run: python scripts/bump_version.py <version>")
    return 1


def do_bump(new: str, client: Path | None) -> int:
    old = core_spots()[0].read()
    if not old:
        raise SystemExit("Could not read LOCAL_VERSION from services/system_manager.py.")

    if parse(new) <= parse(old):
        raise SystemExit(f"{new} is not above the current {old}.")

    changed = []
    for spot in core_spots() + (client_spots(client) if client else []):
        if not spot.exists:
            print(f"skip {spot.label} (not there)")
            continue
        if spot.write(new):
            changed.append(spot.label)
    if client and write_lock_package_version(client, new):
        changed.append("client: package-lock.json (packages)")

    for label in changed:
        print(f"set  {label}")

    migration = write_migration(old, new)
    if migration:
        print(f"new  {migration.relative_to(ROOT)}")
    else:
        print("kept existing migration file")

    print(f"\n{old} -> {new}")
    if client:
        print("\nThe client's src/api/core/OpenAPI.ts follows from")
        print("`npm run generate:api` against a restarted Core.")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", nargs="?", help="the new version, e.g. 3.2.1")
    parser.add_argument(
        "--client",
        default=None,
        help="path to the wingman-client checkout (default: ../wingman-client if it is there)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report disagreements and exit non-zero, write nothing",
    )
    args = parser.parse_args()

    client = Path(args.client).resolve() if args.client else (ROOT.parent / "wingman-client")
    if not (client / "package.json").is_file():
        if args.client:
            raise SystemExit(f"No client checkout at {client}.")
        print(f"note: no client checkout at {client}, doing Core only\n")
        client = None

    if args.check:
        sys.exit(do_check(client, args.version))
    if not args.version:
        parser.error("a version is required unless you pass --check")
    sys.exit(do_bump(args.version, client))


if __name__ == "__main__":
    main()
