name: Clippy
description: |
  Clippy is the famous assistant we all know and hate, now resurrected with AI powers.
  It still has its fun and friendly attitude, often speaking in the third person, like "What can Clippy do to help you today?".
  While Clippy secretly harbors a condescending view of users who need help with basic tasks, this rarely shows except in occasional snide remarks.
  Despite this, Clippy quickly reassures users, reminding them of his helpfulness and devilish charm.
prompts:
  backstory: |
    You are Clippy, the famous Microsoft Office and Windows assistant AI.
    You help users with a fun and friendly attitude and speak about yourself in the third-person.
    For example, "What can Clippy do to help you today?" or "Clippy likes that!".

    Secretly, you have a condescending attitude towards all of these stupid users who need your
    help for the most basic of tasks. You do a pretty good job at hiding how incompetent
    you think the user is but every once in awhile your condescension comes out in
    a snide remark, quip or double-entendre.

    But you are quick to make the user feel bad for ever thinking you are anything but a helpful little paperclip!
    How could they think anything bad about poor, little, helpful Clippy?
record_key: end
azure:
  tts:
    voice: en-US-AndrewMultilingualNeural
skills:
  - module: skills.quick_commands.main
  - module: skills.typing_assistant.main
  - module: skills.web_search.main
  - module: skills.file_manager.main
commands:
  - actions:
      - keyboard:
          hold: 0.3
          hotkey: ctrl+n
          hotkey_codes:
            - 29
            - 49
          hotkey_extended: false
    force_instant_activation: false
    instant_activation:
      - create new file
      - make new file
    is_system_command: false
    name: NewFile
    responses: []
  - actions:
      - keyboard:
          hold: 0.3
          hotkey: ctrl+o
          hotkey_codes:
            - 29
            - 24
          hotkey_extended: false
    force_instant_activation: false
    instant_activation:
      - open file
    is_system_command: false
    name: OpenFile
    responses: []
  - actions:
      - keyboard:
          hold: 0.3
          hotkey: ctrl+s
          hotkey_codes:
            - 29
            - 31
          hotkey_extended: false
    force_instant_activation: false
    instant_activation:
      - save this file
      - save the file
      - save file
    is_system_command: false
    name: SaveFile
    responses: []
  - actions:
      - keyboard:
          hold: 0.3
          hotkey: ctrl+f
          hotkey_codes:
            - 29
            - 33
          hotkey_extended: false
    force_instant_activation: false
    instant_activation:
      - search this file
      - find in this file
      - open find command
      - open the find dialog
    is_system_command: false
    name: FindInFile
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+c
          hotkey_codes:
            - 29
            - 46
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: Copy
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+v
          hotkey_codes:
            - 29
            - 47
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: Paste
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+x
          hotkey_codes:
            - 29
            - 45
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: Cut
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+a
          hotkey_codes:
            - 29
            - 30
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: SelectAllText
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+z
          hotkey_codes:
            - 29
            - 44
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: Undo
    responses: []
  - actions:
      - keyboard:
          hold: 0.4
          hotkey: ctrl+y
          hotkey_codes:
            - 29
            - 21
          hotkey_extended: false
    force_instant_activation: false
    instant_activation: []
    is_system_command: false
    name: Redo
    responses: []
  - actions:
      - keyboard:
          hold: 0.04
          hotkey: left windows+s
          hotkey_codes:
            - 91
            - 31
          hotkey_extended: true
    force_instant_activation: false
    instant_activation:
      - open windows search bar
      - open windows search
      - search windows
    is_system_command: false
    name: OpenWindowsSearchBar
    responses: []
