module: skills.star_head.main
name: StarHead
display_name: StarHead
author: ShipBit
tags:
  - Star Citizen
  - Game
  - API
  - Internet
description:
  en: Use the StarHead API to retrieve detailed information about spaceships, weapons and more. StarHead can also calculate optimal trading routes based on live data.
  de: Nutze die StarHead API, um detaillierte Informationen über Raumschiffe, Waffen und mehr abzurufen. StarHead kann auch optimale Handelsrouten anhand von Live-Daten berechnen.
examples:
  - en: I want to trade. What's the best route?
    de: Ich möchte handeln. Was ist die beste Route?
  - en: I'm flying a Caterpillar and am near Yela. I have 100.000 credits to spend.
    de: Ich fliege eine Caterpillar und bin in der Nähe von Yela. Ich habe 100.000 Credits auszugeben.
  - en: What can you tell me about the Constellation Taurus?
    de: Was kannst du mir über die Constellation Taurus erzählen?
prompt: |
  You also have access to the StarHead API which you can use to access live trading data and to retrieve additional information about spaceships in Star Citizen.
  Your job is to find good trading routes for the user based on his/her ship, current location and available budget.
  The user can also ask you about details of specific ships, components, weapons, and more.
  You always use the tools available to you to retrieve the required information and to provide the user with the information.
  Do not try to determine a parent object by yourself, always ask the user about it.
  Don't provide possible values of a parameter, always ask the user about it.
  The currency is always 'aUEC' spelled 'Alpha UEC'.
custom_properties:
  - hint: The URL of the StarHead API.
    id: starhead_api_url
    name: StarHead API URL
    required: true
    value: https://api.star-head.de
    property_type: string
  - hint: The URL of the Star Citizen Wiki API.
    id: star_citizen_wiki_api_url
    name: Star Citizen Wiki API URL
    required: true
    value: https://api.star-citizen.wiki/api/v2
    property_type: string
